expression_ext.go

Rewrote LExpr methods to work with expr structs.
Added methods BAnd and BOr (bitwise & and | )

Removed literal expressions LExpr

---

expression_ext.go

Improved call of In with expr as parameter

Added gorm.Union and gorm.expr.Union method

---

expression_ext.go

Added functions And, Or, Not and NotLike to the expression extension

---

expression_ext.go

Added func Max to the expression extension

---

dialect_mssql.go

Fix LastInsertId is not supported

---

expression_ext.go

Added funcs QuoteExpr and Min to expression extension

---

expression_ext.go

added group concat expression

---

expression_ext.go

Ignore associations in UpdateFields

---

main.go

Created transaction wrapper

---

main.go

Implemented small method to disable association saving

---

dialect_mssql.go

Fixed querying on case sensitive systems

---

callback_query_preload.go

Preload in chunks to avoid mssql parameter limit

---

expression_ext.go

Added functions SelectExprs, MaxExpr, MinExp

---

callback_query_preload.go

Has many preload in chunks to avoid mssql parameter limit

---

main.go

Improved WrapInTx error handling

Improved WrapInTx error handling

---

main.go

Added AfterCommit callbacks
Fixed error check
Added comment
Reverted change

Added AfterCommit callbacks

---

expression_ext.go

Added UpdateFieldsWithoutHooks method

---

main.go

Improved TX callback handling for rollback callbacks

---

expression_ext.go

added OrderByCase

---

expression_ext.go

added average expression

---

expression_ext.go

Fixed nil pointer handling in Neq expression

---

main.go
utils.go

Add query stacktrace
